["string/empty"]
name = "Blank Reflection"
modid = "moreiotas"
modName = "MoreIotas"
pattern = '{"hexcasting:type": "hexcasting:pattern", "hexcasting:data": {"angles": [B; 4b, 0b, 2b, 0b, 4b], "start_dir": 2b}}'
args = "→ str"
description = "Add an empty string to the stack, useful for combining with other strings."

["string/space"]
name = "Spacing Reflection"
modid = "moreiotas"
modName = "MoreIotas"
pattern = '{"hexcasting:type": "hexcasting:pattern", "hexcasting:data": {"angles": [B; 4b, 0b, 2b, 0b, 4b, 4b, 0b, 0b], "start_dir": 2b}}'
args = "→ str"
description = "Add a blank space string to the stack, useful for combining with other strings."

["string/comma"]
name = "Comma Reflection"
modid = "moreiotas"
modName = "MoreIotas"
pattern = '{"hexcasting:type": "hexcasting:pattern", "hexcasting:data": {"angles": [B; 5b, 4b], "start_dir": 1b}}'
args = "→ str"
description = "Add a comma string to the stack, useful for combining with other strings."

["string/newline"]
name = "Breaking Reflection"
modid = "moreiotas"
modName = "MoreIotas"
pattern = '{"hexcasting:type": "hexcasting:pattern", "hexcasting:data": {"angles": [B; 0b, 4b, 4b, 0b, 4b, 0b], "start_dir": 1b}}'
args = "→ str"
description = "Add a string to the stack representing a break between lines, useful for combining with other strings."

["string/block/get"]
name = "Reader's Purification"
modid = "moreiotas"
modName = "MoreIotas"
pattern = '{"hexcasting:type": "hexcasting:pattern", "hexcasting:data": {"angles": [B; 4b, 0b, 5b, 0b, 4b, 0b, 5b, 1b], "start_dir": 1b}}'
args = "vec → str | [str]"
description = "Removes a vector from the stack. If that vector is pointing at a sign or lectern, it returns that sign or lectern's text to the stack. Otherwise, it returns null."

["string/block/set"]
name = "Write"
modid = "moreiotas"
modName = "MoreIotas"
pattern = '{"hexcasting:type": "hexcasting:pattern", "hexcasting:data": {"angles": [B; 2b, 0b, 1b, 0b, 2b, 0b, 1b, 5b], "start_dir": 4b}}'
args = "vec, str | [str] →"
description = "Removes a vector and a string from the stack. If that vector is pointing at a sign or lectern, it writes that string to that sign or lectern. Costs a hundredth of an Amethyst Dust."

["string/chat/caster"]
name = "Whisper Reflection"
modid = "moreiotas"
modName = "MoreIotas"
pattern = '{"hexcasting:type": "hexcasting:pattern", "hexcasting:data": {"angles": [B; 0b, 4b, 5b, 4b], "start_dir": 1b}}'
args = "→ str"
description = "Adds the last message the caster sent to the stack as a string."

["string/chat/all"]
name = "Listener's Reflection"
modid = "moreiotas"
modName = "MoreIotas"
pattern = '{"hexcasting:type": "hexcasting:pattern", "hexcasting:data": {"angles": [B; 0b, 2b, 1b, 2b], "start_dir": 1b}}'
args = "→ str"
description = "Adds the last message anyone sent to the stack as a string."

["string/chat/prefix/set"]
name = "Sifter's Gambit"
modid = "moreiotas"
modName = "MoreIotas"
pattern = '{"hexcasting:type": "hexcasting:pattern", "hexcasting:data": {"angles": [B; 5b, 0b, 4b, 5b, 4b], "start_dir": 2b}}'
args = "str | null →"
description = "Accepts a string; All future chat messages starting with that string won't be seen by others, and only messages prefixed with that string can be read by Whisper Reflection."

["string/chat/prefix/get"]
name = "Sifter's Reflection"
modid = "moreiotas"
modName = "MoreIotas"
pattern = '{"hexcasting:type": "hexcasting:pattern", "hexcasting:data": {"angles": [B; 1b, 0b, 2b, 1b, 2b], "start_dir": 0b}}'
args = "→ str | null"
description = "Returns the last string you passed to Sifter's Gambit."

["string/iota"]
name = "Scrivener's Purification"
modid = "moreiotas"
modName = "MoreIotas"
pattern = '{"hexcasting:type": "hexcasting:pattern", "hexcasting:data": {"angles": [B; 0b, 4b, 0b, 5b, 0b, 4b, 0b, 4b, 0b], "start_dir": 1b}}'
args = "any → str"
description = "Converts the iota on top of the stack into a string."

["string/action"]
name = "Patternmaster's Purification"
modid = "moreiotas"
modName = "MoreIotas"
pattern = '{"hexcasting:type": "hexcasting:pattern", "hexcasting:data": {"angles": [B; 0b, 2b, 0b, 1b, 0b, 2b, 0b, 2b, 0b], "start_dir": 5b}}'
args = "pattern → str | null"
description = "Converts the pattern on top of the stack into the string for that pattern's name. If there is no action associated with that pattern, or if the associated pattern is a Great Spell, it returns null."

["string/add"]
name = "Concatenation Distillation"
modid = "moreiotas"
modName = "MoreIotas"
pattern = '{"hexcasting:type": "hexcasting:pattern", "hexcasting:data": {"angles": [B; 0b, 4b, 4b, 0b, 4b, 5b, 0b, 4b, 0b, 5b, 5b], "start_dir": 0b}}'
args = "str, str → str"
description = "Removes the top two strings from the stack and combines them together."

["string/split"]
name = "Separation Distillation"
modid = "moreiotas"
modName = "MoreIotas"
pattern = '{"hexcasting:type": "hexcasting:pattern", "hexcasting:data": {"angles": [B; 4b, 5b, 0b, 4b, 5b, 4b], "start_dir": 1b}}'
args = "str, str → [str]"
description = "Removes the top two strings from the stack and splits the first string, using the second string as the delimiter and returning as a list."

["string/parse"]
name = "Input Purification"
modid = "moreiotas"
modName = "MoreIotas"
pattern = '{"hexcasting:type": "hexcasting:pattern", "hexcasting:data": {"angles": [B; 4b, 5b, 0b, 4b, 5b], "start_dir": 1b}}'
args = "str → num | null"
description = "Removes a string from the top of the stack and returns the number that string parses as (or null if it doesn't parse)."

["string/find"]
name = "Discoverer's Distillation"
modid = "moreiotas"
modName = "MoreIotas"
pattern = '{"hexcasting:type": "hexcasting:pattern", "hexcasting:data": {"angles": [B; 0b, 4b, 5b, 0b, 0b, 4b, 5b, 4b], "start_dir": 1b}}'
args = "str, str → num"
description = "Removes two strings from the top of the stack, and returns the first index of the first string where the second string is a substring."

["string/sub"]
name = "Winnowing Distillation"
modid = "moreiotas"
modName = "MoreIotas"
pattern = '{"hexcasting:type": "hexcasting:pattern", "hexcasting:data": {"angles": [B; 4b, 5b, 0b, 0b, 4b, 5b, 0b, 4b, 4b, 2b], "start_dir": 1b}}'
args = "str, num, num → str"
description = "Removes a string and two positive integers from the top of the stack, and returns the substring from the first to the second (inclusive first, exclusive second)."

["string/len"]
name = "Length Distillation: Str"
modid = "moreiotas"
modName = "MoreIotas"
pattern = '{"hexcasting:type": "hexcasting:pattern", "hexcasting:data": {"angles": [B; 0b, 4b, 5b, 4b, 1b, 4b, 5b], "start_dir": 1b}}'
args = "str → num"
description = "Removes a string and returns its length."

["string/case"]
name = "Case Distillation"
modid = "moreiotas"
modName = "MoreIotas"
pattern = '{"hexcasting:type": "hexcasting:pattern", "hexcasting:data": {"angles": [B; 2b, 0b, 0b, 2b, 0b, 0b, 2b, 0b, 2b, 2b], "start_dir": 4b}}'
args = "str, bool | null → str"
description = "Removes a string and a bool or null. If it was true, return the string in upper case. If false, lowercase. If null, toggle each character's case."

["matrix/make"]
name = "Transformation Purification"
modid = "moreiotas"
modName = "MoreIotas"
pattern = '{"hexcasting:type": "hexcasting:pattern", "hexcasting:data": {"angles": [B; 4b, 0b, 0b, 4b, 1b, 4b, 0b, 0b, 4b, 4b, 2b, 0b, 4b], "start_dir": 3b}}'
args = "num | vec | list → mat"
description = "Converts the iota on top of the stack into a matrix. This iota can be a number, vector, or list."

["matrix/unmake"]
name = "Restoration Purification"
modid = "moreiotas"
modName = "MoreIotas"
pattern = '{"hexcasting:type": "hexcasting:pattern", "hexcasting:data": {"angles": [B; 2b, 0b, 0b, 2b, 5b, 2b, 0b, 0b, 2b, 2b, 4b, 0b, 2b], "start_dir": 2b}}'
args = "mat → num | vec | list"
description = "Converts the iota on top of the stack back from a matrix into a number, vector, or list depending on the vector's size."

["matrix/identity"]
name = "Identity Purification"
modid = "moreiotas"
modName = "MoreIotas"
pattern = '{"hexcasting:type": "hexcasting:pattern", "hexcasting:data": {"angles": [B; 4b, 0b, 0b, 4b, 1b, 4b, 0b, 0b, 4b, 5b, 0b], "start_dir": 3b}}'
args = "int â‰¥ 0 → mat"
description = "Accepts a positive integer n, and returns an n by n matrix with 1 along the diagonal and 0 elsewhere."

["matrix/zero"]
name = "Zero Distillation"
modid = "moreiotas"
modName = "MoreIotas"
pattern = '{"hexcasting:type": "hexcasting:pattern", "hexcasting:data": {"angles": [B; 4b, 0b, 0b, 4b, 1b, 4b, 0b, 0b, 4b], "start_dir": 3b}}'
args = "int â‰¥ 0, int â‰¥ 0 → mat"
description = "Accepts positive integers n and m, and returns an n by m matrix of zeros."

["matrix/rotation"]
name = "Rotation Distillation"
modid = "moreiotas"
modName = "MoreIotas"
pattern = '{"hexcasting:type": "hexcasting:pattern", "hexcasting:data": {"angles": [B; 4b, 0b, 0b, 4b, 1b, 4b, 0b, 0b, 4b, 0b, 4b, 0b, 2b, 2b, 0b], "start_dir": 3b}}'
args = "vec, num → mat"
description = "Accepts a vec v and number Î¸, and returns a matrix representing rotating by Î¸ radians around v."

["matrix/add"]
name = "Addition Distillation: Matrix"
modid = "moreiotas"
modName = "MoreIotas"
pattern = '{"hexcasting:type": "hexcasting:pattern", "hexcasting:data": {"angles": [B; 0b, 4b, 4b, 0b, 4b, 0b, 4b, 1b, 4b, 0b, 0b, 4b, 1b, 4b], "start_dir": 1b}}'
args = "mat, mat → mat"
description = "Adds two matrices together; they must have the same number of columns and rows."

["matrix/mul"]
name = "Multiplication Distillation: Matrix"
modid = "moreiotas"
modName = "MoreIotas"
pattern = '{"hexcasting:type": "hexcasting:pattern", "hexcasting:data": {"angles": [B; 0b, 4b, 5b, 4b, 0b, 4b, 0b, 0b, 4b, 1b, 4b, 0b, 0b], "start_dir": 2b}}'
args = "mat, mat → mat"
description = "Multiplies the first n by m matrix with an m by p matrix."

["matrix/transpose"]
name = "Transpose Purification"
modid = "moreiotas"
modName = "MoreIotas"
pattern = '{"hexcasting:type": "hexcasting:pattern", "hexcasting:data": {"angles": [B; 0b, 0b, 4b, 1b, 4b, 0b, 0b, 4b, 1b, 2b, 1b], "start_dir": 1b}}'
args = "mat → mat"
description = "Accepts an n by m matrix and returns an m by n matrix where every entry has been flipped along the diagonal."

["matrix/inverse"]
name = "Inverse Purification"
modid = "moreiotas"
modName = "MoreIotas"
pattern = '{"hexcasting:type": "hexcasting:pattern", "hexcasting:data": {"angles": [B; 0b, 0b, 2b, 5b, 2b, 0b, 0b, 2b, 5b, 4b, 5b], "start_dir": 4b}}'
args = "mat → mat"
description = "Accepts an n by n matrix and returns the n by n matrix such that in*out = identity."

["matrix/determinant"]
name = "Determinant Purification"
modid = "moreiotas"
modName = "MoreIotas"
pattern = '{"hexcasting:type": "hexcasting:pattern", "hexcasting:data": {"angles": [B; 4b, 1b, 4b, 0b, 0b, 4b, 1b, 4b, 0b, 4b, 0b], "start_dir": 4b}}'
args = "mat → num"
description = "Accepts a square matrix and returns the determinant of that matrix. Mishaps for matrices larger than 4x4."

["matrix/concat/vert"]
name = "Tower Distillation"
modid = "moreiotas"
modName = "MoreIotas"
pattern = '{"hexcasting:type": "hexcasting:pattern", "hexcasting:data": {"angles": [B; 4b, 0b, 0b, 4b, 1b, 4b, 0b, 0b, 4b, 0b, 4b, 0b, 2b, 1b, 2b, 0b, 4b], "start_dir": 3b}}'
args = "mat, mat → mat"
description = "Accepts an n by m matrix and an n by p matrix and produces an n by (m+p) matrix by putting the first matrix on top of the second."

["matrix/concat/hori"]
name = "Sprawling Distillation"
modid = "moreiotas"
modName = "MoreIotas"
pattern = '{"hexcasting:type": "hexcasting:pattern", "hexcasting:data": {"angles": [B; 2b, 0b, 0b, 2b, 5b, 2b, 0b, 0b, 2b, 0b, 2b, 0b, 4b, 5b, 4b, 0b, 2b], "start_dir": 2b}}'
args = "mat, mat → mat"
description = "Accepts an m by n matrix and a p by n matrix and produces an (m+p) by n matrix by putting the first matrix to the left of the second."

["matrix/split/vert"]
name = "Toppling Gambit"
modid = "moreiotas"
modName = "MoreIotas"
pattern = '{"hexcasting:type": "hexcasting:pattern", "hexcasting:data": {"angles": [B; 4b, 0b, 2b, 1b, 2b, 0b, 4b, 0b, 4b, 0b, 0b, 4b, 1b, 4b, 0b, 0b, 4b], "start_dir": 2b}}'
args = "mat, num → mat, mat"
description = "Accepts an n by m matrix and an int from 0 to n, and returns two matrices created by splitting the input matrix vertically at the inputted int."

["matrix/split/hori"]
name = "Mitosis Gambit"
modid = "moreiotas"
modName = "MoreIotas"
pattern = '{"hexcasting:type": "hexcasting:pattern", "hexcasting:data": {"angles": [B; 2b, 0b, 4b, 5b, 4b, 0b, 2b, 0b, 2b, 0b, 0b, 2b, 5b, 2b, 0b, 0b, 2b], "start_dir": 3b}}'
args = "mat, num → mat, mat"
description = "Accepts an n by m matrix and an int from 0 to m, and returns two matrices created by splitting the input matrix horizontally at the inputted int."
