name: Release Extension

on:
  push:
    tags:
      - "v*" # 当推送 v 开头的 tag 时触发
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Build Extension
        run: pnpm run package-extension
      - name: Upload File
        uses: actions/upload-artifact@v4
        with:
          name: hex casting
          path: |
              *.vsix
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref }}
          body: TODO New Release.
          draft: false
          prerelease: false
          files: |
            *.vsix
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to VS Code Marketplace
        run: pnpm vsce  --no-dependencies -p ${{ secrets.VSCODE_MARKETPLACE_TOKEN }}
        if: success()
